id: DD18EC6EC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-23T08:32:13+00:00'
last_modified: '2022-05-30T07:21:50.878488+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    1b11:
      image_group_id: I1PD95892
      title: འཕགས་མ་ལྷ་མོ་སྒྲོལ་མ་ལ་བསྟོད་པ།
      total_pages: 1464
      order: 47
      base_file: 1b11.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
